name: mystrath
description: "A new Flutter project."

publish_to: 'none' # Remove this line if you wish to publish to pub.dev


version: 1.0.0+1

environment:
  sdk: '>=3.3.4 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.6
  google_fonts: ^6.2.1
  carousel_slider: ^5.0.0
  location: ^7.0.1
  provider: ^6.1.2
  flutter_polyline_points: ^2.1.0
  google_maps_flutter: ^2.0.10
  flutter_svg: ^2.0.10+1
  flutter_google_map_polyline_point: ^0.0.1
  shared_preferences: ^2.0.8
  get: ^4.6.6
  cloud_firestore: ^5.0.0
  firebase_core: ^3.0.0
  cached_network_image: ^3.4.0


dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0

flutter:
 uses-material-design: true


 assets:
   - assets/
